import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Testimonials from '../components/Testimonials'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

     <main className='max-w-screen-2xl mx-auto'>
      {/* <CopiedNavbar /> */}
      <Banner />
      <Testimonials />
     </main>

     <footer>
      <Footer />
     </footer>
    </div>
  )
}
